### ISSUE TITLE
Possible bug with OP_CHECKSIG

### ISSUE THREAD

**Issue by vinarmani** [gcash/meep#4]
The following command fails in meep on the final OP_CHECKSIG:

`meep debug --idx=0 --amt=10200 --pkscript=a9148baa7f7c897382d277f6eb8a61e2666358364b2387 --tx=010000000118bff68d350eed902b1c3e3fcc4efebdcd2071e6ec8fab2b8462fc950fe49e9f00000000fd1a01473044022065b2ac31e78f41e6272b7ba6c38fc7b27a9d1aecf71b611fe07ac702f0050b14022038f56b9d2bd491448224f2af8072fdd9d12d88a3849a95b1b30fdd537ebcc4a7412103c1694a3fc1365d274d4018ff084fce836deca598f80067d3eee4a639bb79f3b4463044022073d326debb068da4e7c99d2a917355bf708c7f5bcca02837ca12af7efbf1b1b70220328a3c2a8035e5a6bf28a640d6ed0367450124623e1c6f51c71504fe56ce47bb05edb309b45f4c6176537f7cb175021860a15379a97c6314ac656e2dd5378ca9c45fd5cd44aa7da87c7bfa82886714da74026d67264c0acfede38e8302704ef7d8cfb288682102ca65d71ee988f11435ca59534e24f200b2053e2f65e8836493f1e56e4a9c2327bbacfeffffff0141060000000000001976a914ac656e2dd5378ca9c45fd5cd44aa7da87c7bfa8288acedb30900`

However, this is indeed a valid transaction and is on the blockchain at https://explorer.bitcoin.com/bch/tx/dbe0a2baa0857606375775fde2a89a6abaac204246ef0ccc13b9a776d0e0b3d7

**Comment by zquestz** [comment]
This is indeed the wrong command!

```
meep debug --idx=0 --amt=2000 --pkscript=a9148baa7f7c897382d277f6eb8a61e2666358364b2387 --tx=010000000118bff68d350eed902b1c3e3fcc4efebdcd2071e6ec8fab2b8462fc950fe49e9f00000000fd1a01473044022065b2ac31e78f41e6272b7ba6c38fc7b27a9d1aecf71b611fe07ac702f0050b14022038f56b9d2bd491448224f2af8072fdd9d12d88a3849a95b1b30fdd537ebcc4a7412103c1694a3fc1365d274d4018ff084fce836deca598f80067d3eee4a639bb79f3b4463044022073d326debb068da4e7c99d2a917355bf708c7f5bcca02837ca12af7efbf1b1b70220328a3c2a8035e5a6bf28a640d6ed0367450124623e1c6f51c71504fe56ce47bb05edb309b45f4c6176537f7cb175021860a15379a97c6314ac656e2dd5378ca9c45fd5cd44aa7da87c7bfa82886714da74026d67264c0acfede38e8302704ef7d8cfb288682102ca65d71ee988f11435ca59534e24f200b2053e2f65e8836493f1e56e4a9c2327bbacfeffffff0141060000000000001976a914ac656e2dd5378ca9c45fd5cd44aa7da87c7bfa8288acedb30900
```

The value is 2000 not 10200. =)
